### ISSUE TITLE
Properties Panel text colour in Chrome

### ISSUE THREAD

**Issue by robsilv** [CadetEditor/CadetEditor-as#1]
Looks disabled. Maybe change to white?

**Comment by edsilv** [comment]
make it the same grey as the labels.

**Comment by robsilv** [comment]
The problem is that it already is the same grey as the labels if you view in FF or AIR. Not sure why Chrome is doing this, probably an issue with the Pepper version of Flash Player.

**Comment by robsilv** [comment]
Note to self: Same problem occurs in all dynamic textfields (e.g. Save As dialogue)
