### ISSUE TITLE
Pre-select text in Save As Panel

### ISSUE THREAD

**Issue by edsilv** [CadetEditor/CadetEditor-as#3]
When saving to a shared object in the browser (chrome) (on the basic physics example) when clicking in the filename box 'untitled' doesn't clear.

**Comment by robsilv** [comment]
Doesn't clear automatically, or can't be selected and cleared?

**Comment by edsilv** [comment]
doesn't clear automatically

**Comment by robsilv** [comment]
This means that it behaves the same way as all the other selectable text in the editor, e.g. the Properties Inspector.

**Comment by edsilv** [comment]
hmm, maybe have that as an enhancement then. you definitely expect it to clear when clicking on it.

**Comment by robsilv** [comment]
I disagree that this is the expected behaviour. I've just tried saving a file in Flash Builder and Photoshop, both programs behave the same way as CadetEditor currently behaves.

**Comment by edsilv** [comment]
In my photoshop, the 'untitled.psd' text is pre-selected, so as soon as you type it's overwritten. Maybe that's the way forward. You expect to be able to just click and start typing. Clicking on it and it inserting the cursor somewhere within 'untitled' is definitely rubbish - and easily fixable, surely?

**Comment by edsilv** [comment]
try saving a web page for example in chrome. that does the same thing. file name is pre-selected.

**Comment by robsilv** [comment]
Ok, pre-selected is a different feature request, which is what Flash Builder does too. Will look into that.

**Comment by robsilv** [comment]
Closing bug as this has been resubmitted as an enhancement.
