### ISSUE TITLE
Remove HH Barebones 2D example

### ISSUE THREAD

**Issue by edsilv** [CadetEditor/CadetEditor-as#6]
The HH BareBones2D example doesn't have any drawing tools. Why bother having it at all?

**Comment by robsilv** [comment]
The idea is that you could completely reconstruct the HH game by hand in the editor. For instance, I've been testing certain bugs by just creating an ImageSkin and selecting the plane texture from the TextureAtlas.

**Comment by edsilv** [comment]
Ok, but for someone like me it's a bit of a mystery. I guess it's fine to leave it.
